const WHO_WORKFORCE_SOURCE = "https://www.who.int/publications/i/item/9789241512404";
const CANONICAL_SPECIALTY_SOURCE = "https://hl7.org/fhir/R5/practitionerrole.html";

export const PRACTITIONER_PROFESSIONS = [
  ["medicine", "Medical Practitioner", "221"],
  ["dentistry", "Dental Practitioner", "2261"],
  ["nursing", "Nursing Professional", "2221"],
  ["midwifery", "Midwifery Professional", "2222"],
  ["pharmacy", "Pharmacist", "2262"],
  ["psychology", "Psychologist", "2634"],
  ["physiotherapy", "Physiotherapist", "2264"],
  ["occupational-therapy", "Occupational Therapist", "2269"],
  ["speech-language-therapy", "Speech and Language Therapist", "2266"],
  ["dietetics-nutrition", "Dietitian and Nutritionist", "2265"],
  ["optometry", "Optometrist", "2267"],
  ["podiatry", "Podiatrist", "2269"],
  ["audiology", "Audiologist", "2266"],
  ["radiography", "Medical Imaging Professional", "3211"],
  ["medical-laboratory-science", "Medical Laboratory Professional", "3212"],
  ["paramedicine", "Paramedic", "3258"],
  ["social-work", "Health Social Worker", "2635"],
  ["public-health", "Public Health Professional", "2263"],
  [
    "traditional-complementary-medicine",
    "Traditional and Complementary Medicine Practitioner",
    "2230",
  ],
] as const;

export interface ProfessionSeed {
  code: string;
  name: string;
  sourceCode: string;
  sourceSystem: string;
  sourceUri: string;
  sourceVersion: string;
}

export const PROFESSION_SEEDS: readonly ProfessionSeed[] = PRACTITIONER_PROFESSIONS.map(
  ([code, name, sourceCode]) => ({
    code,
    name,
    sourceCode,
    sourceSystem: "WHO health workforce / ISCO-08 mapping",
    sourceUri: WHO_WORKFORCE_SOURCE,
    sourceVersion: "ISCO-08",
  }),
);

const SPECIALTIES = [
  ["general-practice-family-medicine", "General Practice / Family Medicine", "Primary Care"],
  ["internal-medicine", "Internal Medicine", "Medicine"],
  ["adolescent-medicine", "Adolescent Medicine", "Medicine"],
  ["allergy-immunology", "Allergy and Immunology", "Medicine"],
  ["cardiology", "Cardiology", "Medicine"],
  ["clinical-genetics", "Clinical Genetics", "Medicine"],
  ["clinical-pharmacology", "Clinical Pharmacology", "Medicine"],
  ["dermatology", "Dermatology", "Medicine"],
  ["endocrinology-diabetes-metabolism", "Endocrinology, Diabetes and Metabolism", "Medicine"],
  ["gastroenterology", "Gastroenterology", "Medicine"],
  ["geriatric-medicine", "Geriatric Medicine", "Medicine"],
  ["haematology", "Haematology", "Medicine"],
  ["hepatology", "Hepatology", "Medicine"],
  ["infectious-diseases", "Infectious Diseases", "Medicine"],
  ["medical-oncology", "Medical Oncology", "Medicine"],
  ["nephrology", "Nephrology", "Medicine"],
  ["neurology", "Neurology", "Medicine"],
  ["nuclear-medicine", "Nuclear Medicine", "Medicine"],
  ["palliative-medicine", "Palliative Medicine", "Medicine"],
  ["physical-medicine-rehabilitation", "Physical Medicine and Rehabilitation", "Medicine"],
  ["pulmonology-respiratory-medicine", "Pulmonology / Respiratory Medicine", "Medicine"],
  ["rheumatology", "Rheumatology", "Medicine"],
  ["sleep-medicine", "Sleep Medicine", "Medicine"],
  ["sports-exercise-medicine", "Sports and Exercise Medicine", "Medicine"],
  ["tropical-medicine", "Tropical Medicine", "Medicine"],
  ["paediatrics", "Paediatrics", "Paediatrics"],
  ["neonatology", "Neonatology", "Paediatrics"],
  ["paediatric-cardiology", "Paediatric Cardiology", "Paediatrics"],
  ["paediatric-endocrinology", "Paediatric Endocrinology", "Paediatrics"],
  ["paediatric-gastroenterology", "Paediatric Gastroenterology", "Paediatrics"],
  ["paediatric-haematology-oncology", "Paediatric Haematology and Oncology", "Paediatrics"],
  ["paediatric-infectious-diseases", "Paediatric Infectious Diseases", "Paediatrics"],
  ["paediatric-nephrology", "Paediatric Nephrology", "Paediatrics"],
  ["paediatric-neurology", "Paediatric Neurology", "Paediatrics"],
  ["paediatric-pulmonology", "Paediatric Pulmonology", "Paediatrics"],
  [
    "developmental-behavioural-paediatrics",
    "Developmental and Behavioural Paediatrics",
    "Paediatrics",
  ],
  ["obstetrics-gynaecology", "Obstetrics and Gynaecology", "Women's Health"],
  ["maternal-fetal-medicine", "Maternal-Fetal Medicine", "Women's Health"],
  ["gynaecologic-oncology", "Gynaecologic Oncology", "Women's Health"],
  ["reproductive-medicine-infertility", "Reproductive Medicine and Infertility", "Women's Health"],
  ["urogynecology-pelvic-medicine", "Urogynecology and Pelvic Medicine", "Women's Health"],
  ["general-surgery", "General Surgery", "Surgery"],
  ["cardiothoracic-surgery", "Cardiothoracic Surgery", "Surgery"],
  ["colorectal-surgery", "Colorectal Surgery", "Surgery"],
  ["endocrine-surgery", "Endocrine Surgery", "Surgery"],
  ["hepatobiliary-pancreatic-surgery", "Hepatobiliary and Pancreatic Surgery", "Surgery"],
  ["neurosurgery", "Neurosurgery", "Surgery"],
  ["oral-maxillofacial-surgery", "Oral and Maxillofacial Surgery", "Surgery"],
  ["orthopaedic-surgery", "Orthopaedic Surgery", "Surgery"],
  ["otolaryngology-head-neck-surgery", "Otolaryngology — Head and Neck Surgery", "Surgery"],
  ["paediatric-surgery", "Paediatric Surgery", "Surgery"],
  ["plastic-reconstructive-surgery", "Plastic and Reconstructive Surgery", "Surgery"],
  ["surgical-oncology", "Surgical Oncology", "Surgery"],
  ["transplant-surgery", "Transplant Surgery", "Surgery"],
  ["trauma-acute-care-surgery", "Trauma and Acute Care Surgery", "Surgery"],
  ["urology", "Urology", "Surgery"],
  ["vascular-surgery", "Vascular Surgery", "Surgery"],
  ["anaesthesiology", "Anaesthesiology", "Acute Care"],
  ["critical-care-medicine", "Critical Care Medicine", "Acute Care"],
  ["emergency-medicine", "Emergency Medicine", "Acute Care"],
  ["pain-medicine", "Pain Medicine", "Acute Care"],
  ["diagnostic-radiology", "Diagnostic Radiology", "Diagnostics"],
  ["interventional-radiology", "Interventional Radiology", "Diagnostics"],
  ["radiation-oncology", "Radiation Oncology", "Diagnostics"],
  ["anatomical-pathology", "Anatomical Pathology", "Diagnostics"],
  ["chemical-pathology", "Chemical Pathology", "Diagnostics"],
  ["clinical-microbiology", "Clinical Microbiology", "Diagnostics"],
  ["forensic-pathology", "Forensic Pathology", "Diagnostics"],
  ["haematopathology", "Haematopathology", "Diagnostics"],
  ["laboratory-medicine", "Laboratory Medicine", "Diagnostics"],
  ["ophthalmology", "Ophthalmology", "Eye Care"],
  ["optometry-primary-care", "Primary Care Optometry", "Eye Care"],
  ["low-vision-rehabilitation", "Low Vision Rehabilitation", "Eye Care"],
  ["psychiatry", "Psychiatry", "Mental and Behavioural Health"],
  [
    "child-adolescent-psychiatry",
    "Child and Adolescent Psychiatry",
    "Mental and Behavioural Health",
  ],
  ["addiction-medicine", "Addiction Medicine", "Mental and Behavioural Health"],
  ["forensic-psychiatry", "Forensic Psychiatry", "Mental and Behavioural Health"],
  ["clinical-psychology", "Clinical Psychology", "Mental and Behavioural Health"],
  ["counselling-psychology", "Counselling Psychology", "Mental and Behavioural Health"],
  ["neuropsychology", "Neuropsychology", "Mental and Behavioural Health"],
  ["health-psychology", "Health Psychology", "Mental and Behavioural Health"],
  ["community-health-nursing", "Community Health Nursing", "Nursing"],
  ["critical-care-nursing", "Critical Care Nursing", "Nursing"],
  ["emergency-nursing", "Emergency Nursing", "Nursing"],
  ["mental-health-nursing", "Mental Health Nursing", "Nursing"],
  ["neonatal-nursing", "Neonatal Nursing", "Nursing"],
  ["oncology-nursing", "Oncology Nursing", "Nursing"],
  ["paediatric-nursing", "Paediatric Nursing", "Nursing"],
  ["perioperative-nursing", "Perioperative Nursing", "Nursing"],
  ["public-health-nursing", "Public Health Nursing", "Nursing"],
  ["midwifery-care", "Midwifery Care", "Midwifery"],
  ["community-pharmacy", "Community Pharmacy", "Pharmacy"],
  ["clinical-pharmacy", "Clinical Pharmacy", "Pharmacy"],
  ["hospital-pharmacy", "Hospital Pharmacy", "Pharmacy"],
  ["oncology-pharmacy", "Oncology Pharmacy", "Pharmacy"],
  ["paediatric-pharmacy", "Paediatric Pharmacy", "Pharmacy"],
  ["psychiatric-pharmacy", "Psychiatric Pharmacy", "Pharmacy"],
  ["geriatric-pharmacy", "Geriatric Pharmacy", "Pharmacy"],
  ["general-dentistry", "General Dentistry", "Dentistry"],
  ["endodontics", "Endodontics", "Dentistry"],
  ["oral-pathology", "Oral and Maxillofacial Pathology", "Dentistry"],
  ["oral-medicine", "Oral Medicine", "Dentistry"],
  ["orthodontics", "Orthodontics", "Dentistry"],
  ["paediatric-dentistry", "Paediatric Dentistry", "Dentistry"],
  ["periodontics", "Periodontics", "Dentistry"],
  ["prosthodontics", "Prosthodontics", "Dentistry"],
  ["public-health-dentistry", "Dental Public Health", "Dentistry"],
  ["musculoskeletal-physiotherapy", "Musculoskeletal Physiotherapy", "Rehabilitation"],
  ["neurological-physiotherapy", "Neurological Physiotherapy", "Rehabilitation"],
  ["cardiorespiratory-physiotherapy", "Cardiorespiratory Physiotherapy", "Rehabilitation"],
  ["paediatric-physiotherapy", "Paediatric Physiotherapy", "Rehabilitation"],
  ["occupational-therapy-rehabilitation", "Occupational Therapy Rehabilitation", "Rehabilitation"],
  ["speech-language-pathology", "Speech and Language Pathology", "Rehabilitation"],
  ["audiological-rehabilitation", "Audiological Rehabilitation", "Rehabilitation"],
  ["clinical-nutrition", "Clinical Nutrition", "Nutrition"],
  ["sports-nutrition", "Sports Nutrition", "Nutrition"],
  ["public-health-nutrition", "Public Health Nutrition", "Nutrition"],
  ["epidemiology", "Epidemiology", "Public Health"],
  ["occupational-health", "Occupational Health", "Public Health"],
  ["environmental-health", "Environmental Health", "Public Health"],
  ["health-policy-management", "Health Policy and Management", "Public Health"],
  ["infection-prevention-control", "Infection Prevention and Control", "Public Health"],
  ["prehospital-emergency-care", "Prehospital Emergency Care", "Paramedicine"],
  ["community-paramedicine", "Community Paramedicine", "Paramedicine"],
] as const;

export interface SpecialtySeed {
  category: string;
  code: string;
  name: string;
  sourceSystem: string;
  sourceUri: string;
  sourceVersion: string;
}

export const SPECIALTY_SEEDS: readonly SpecialtySeed[] = SPECIALTIES.map(
  ([code, name, category]) => ({
    category,
    code,
    name,
    sourceSystem: "Royal Palace canonical specialty catalogue",
    sourceUri: CANONICAL_SPECIALTY_SOURCE,
    sourceVersion: "2026-09",
  }),
);
